server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://192.168.138.134:3339/FileManager
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #邮箱
  mail:
    host: smtp.qq.com
    username: c.jong@qq.com
    password: tsuldibuddardhae
    port: 587

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#文件上传路径
file:
  upload:
    path: D:\upload


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/hjong/mapper/xml/*.xml







